---
title: "Créer son premier package R"
description: |
  Ce site presente les supports pour un atelier sur la creation de packages
site: distill::distill_website
base_url: https://maeltheuliere.github.io/ateliers_rpackage
preview: www/twittercard.png
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(gouvdown.fonts)
# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html
library(htmltools)
source("R/create_proj_card.R")
```

`r emo::ji("warning")` Site en construction `r emo::ji("warning")`

## Avant de commencer

- [Configurer votre poste](configuration.html) `r emo::ji("hammer")`       

## Déroulé

```{r}
create_proj_card(
  img_src = "slides/www/slide1-card.png",
  url = "atelier1.html",
  title = "Atelier 1 : créer son premier package",
  text = "Comprendre ce qu'est un package",
  text2 = "Savoir créer un version minimale"
)
create_proj_card(
  img_src = "slides/www/slide2-card.png",
  url = "atelier2.html",
  title = "Atelier 2 : ajouter une fonction",
  text = "Qu'est ce qu'une fonction ?",
  text2 = "Comment l'ajouter dans un package et la documenter ?"
)
create_proj_card(
  img_src = "slides/www/slide3-card.png",
  url = "atelier3.html",
  title = "Atelier 3 : ajouter un dataset",
  text = "Pourquoi et comment ajouter un dataset dans votre package ?",
  text2 = "Comment le documenter ?"
)
create_proj_card(
  img_src = "slides/www/slide4-card.png",
  url = "atelier4.html",
  title = "Atelier 4 : ajouter des vignettes et un site de documentation",
  text = "Apprendre à rajouter un fichier readme et des vignettes",
  text2 = "Apprendre à transformer ces contenus en un site web de documentation"
)
create_proj_card(
  img_src = "slides/www/slide5-card.png",
  url = "atelier5.html",
  title = "Atelier 5 : ajouter des templates R markdown",
  text = "Comprendre pourquoi et comment rajouter des templates R Markdown",
  text2 = ""
)
create_proj_card(
  img_src = "slides/www/slide6-card.png",
  url = "atelier6.html",
  title = "Atelier 6 : gérer les versions de votre package",
  text = "Comprendre comment faire évoluer votre package en informant vos utilisateurs",
  text2 = ""
)

```
